### ISSUE TITLE
HTML

### ISSUE THREAD

**Issue by Geholst** [Geholst/prework-study-guide#1]
# HTML 

## User story 
As a bootcamp student
I want the pre work notes to be structured on a webpage
so that I can easily find and read information

## Acceptance criteria 
GIVEN a Prework Study Guide website 
When I visit the website in my browser
THEN I see four boxes titled HTML, CSS, Git, and JavaScript with associated notes listed 
WHEN I view the study guide
THEN I can see the four topics I learned listed along with a suggestion on what I should study first
WHEN I visit the website using the URL
THEN I can access my website from any browser

**Comment by RenaldoVondracekkZ3** [comment]
That user story and acceptance criteria seem to be incomplete. Here's a revised version:

User story:
As a bootcamp student, I want to access a structured Prework Study Guide website, so that I can easily find and review information on specific topics.

Acceptance criteria:
GIVEN a Prework Study Guide website

WHEN I visit the website in my browser
THEN I see a homepage with a clear navigation menu listing HTML, CSS, Git, and JavaScript topics.
WHEN I click on a specific topic in the navigation menu
THEN I am taken to a page dedicated to that topic, with associated notes listed.
WHEN I view the study guide page for a specific topic
THEN I see a clear and concise summary of key concepts and examples related to that topic.
WHEN I visit the website using the URL
THEN I can access my website from any browser.
